from .syntax import SyntaxExtractor
from .semantics import SemanticsExtractor
from .contracts import ContractsExtractor
from .dependencies import DependenciesExtractor
from .persistence import PersistenceExtractor
from .events import EventsExtractor
from .architecture import ArchitectureExtractor
from .specs import SpecsExtractor
from .tests import TestsExtractor
from .evolution import EvolutionExtractor
