"""
CORE-08: Metadata Engine

Every artifact gets metadata automatically maintained.
UUID, Owner, Version, Semantic Type, Dependencies, Generated By,
Source, Compiler, Validation State, Certification, Timestamp,
Tags, Security Level, Lifecycle.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from typing import Any, Protocol

from genesis.utils.identity import generate_id


class EventBusProtocol(Protocol):
    """Protocol for event emission. Implemented by events.bus.EventBus."""
    def emit(self, event_type: str, data: dict[str, Any] | None = None) -> None: ...


class MetadataStoreProtocol(Protocol):
    """Protocol for metadata persistence. Implemented by persistence.MetadataStore."""


class MetadataStoreProtocol(Protocol):
    """Protocol for metadata persistence. Implemented by persistence.MetadataStore."""
    def save(self, record: dict[str, Any]) -> None: ...
    def get(self, artifact_id: str) -> dict[str, Any] | None: ...
    def delete(self, artifact_id: str) -> None: ...
    def all(self) -> list[dict[str, Any]]: ...
    def count(self) -> int: ...


class MetadataRecord:
    """Metadata record for a single artifact."""

    def __init__(
        self,
        artifact_path: str,
        semantic_type: str = "unknown",
        version: str = "0.1.0",
    ):
        self.artifact_id = generate_id("meta", 12)
        self.artifact_path = artifact_path
        self.semantic_type = semantic_type
        self.version = version
        self.owner: str = "genesis"
        self.dependencies: list[str] = []
        self.generated_by: str = ""
        self.source: str = ""
        self.compiler_version: str = ""
        self.validation_state: str = "unvalidated"
        self.certification: str = "uncertified"
        self.tags: list[str] = []
        self.security_level: str = "internal"
        self.lifecycle: str = "active"
        self.created_at = datetime.now(timezone.utc).isoformat()
        self.updated_at = self.created_at
        self.size_bytes: int = 0
        self.content_hash: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "artifact_id": self.artifact_id,
            "artifact_path": self.artifact_path,
            "semantic_type": self.semantic_type,
            "version": self.version,
            "owner": self.owner,
            "dependencies": list(self.dependencies),
            "generated_by": self.generated_by,
            "source": self.source,
            "compiler_version": self.compiler_version,
            "validation_state": self.validation_state,
            "certification": self.certification,
            "tags": list(self.tags),
            "security_level": self.security_level,
            "lifecycle": self.lifecycle,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "size_bytes": self.size_bytes,
            "content_hash": self.content_hash,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)


class MetadataEngine:
    """Central metadata engine. Manages metadata for all artifacts."""

    def __init__(self, store_path: str | Path | None = None, metadata_store: MetadataStoreProtocol | None = None, event_bus: EventBusProtocol | None = None):
        self.store_path = Path(store_path) if store_path else None
        self._records: dict[str, MetadataRecord] = {}
        self._metadata_store = metadata_store
        self._bus = event_bus
        if self._metadata_store is not None:
            for record in self._metadata_store.all():
                mr = MetadataRecord(
                    artifact_path=record.get("artifact_path", ""),
                    semantic_type=record.get("semantic_type", "unknown"),
                    version=record.get("version", "0.1.0"),
                )
                mr.artifact_id = record.get("artifact_id", mr.artifact_id)
                mr.owner = record.get("owner", "genesis")
                mr.validation_state = record.get("validation_state", "unvalidated")
                mr.certification = record.get("certification", "uncertified")
                mr.created_at = record.get("created_at", mr.created_at)
                mr.updated_at = record.get("updated_at", mr.updated_at)
                mr.content_hash = record.get("content_hash", "")
                mr.size_bytes = record.get("size_bytes", 0)
                mr.tags = list(record.get("tags", []))
                mr.lifecycle = record.get("lifecycle", "active")
                self._records[mr.artifact_path] = mr

    def _persist(self, record: MetadataRecord):
        if self._metadata_store is not None:
            self._metadata_store.save(record.to_dict())

    def _emit(self, event_type: str, data: dict[str, Any] | None = None) -> None:
        if self._bus is not None:
            self._bus.emit(event_type, data or {})

    def create_record(
        self,
        artifact_path: str,
        semantic_type: str = "unknown",
        version: str = "0.1.0",
    ) -> MetadataRecord:
        record = MetadataRecord(artifact_path, semantic_type, version)
        self._records[artifact_path] = record
        self._persist(record)
        self._emit("metadata.record.created", {
            "artifact_path": artifact_path,
            "semantic_type": semantic_type,
            "version": version,
        })
        return record

    def get_record(self, artifact_path: str) -> MetadataRecord | None:
        return self._records.get(artifact_path)

    def update_record(self, artifact_path: str, **kwargs) -> MetadataRecord | None:
        record = self._records.get(artifact_path)
        if record:
            for key, value in kwargs.items():
                if hasattr(record, key):
                    setattr(record, key, value)
            record.updated_at = datetime.now(timezone.utc).isoformat()
            self._persist(record)
            self._emit("metadata.record.updated", {
                "artifact_path": artifact_path,
                "changes": {k: str(v) for k, v in kwargs.items()},
            })
        return record

    def set_validation_state(self, artifact_path: str, state: str):
        return self.update_record(artifact_path, validation_state=state)

    def set_certification(self, artifact_path: str, cert: str):
        return self.update_record(artifact_path, certification=cert)

    def delete_record(self, artifact_path: str):
        self._records.pop(artifact_path, None)
        if self._metadata_store is not None:
            self._metadata_store.delete(artifact_path)
        self._emit("metadata.record.deleted", {
            "artifact_path": artifact_path,
        })

    def search(self, **filters) -> list[MetadataRecord]:
        results = list(self._records.values())
        for key, value in filters.items():
            results = [r for r in results if getattr(r, key, None) == value]
        return results

    def all_records(self) -> list[MetadataRecord]:
        return list(self._records.values())

    def count(self) -> int:
        return len(self._records)

    def to_dict(self) -> dict[str, Any]:
        return {
            "record_count": len(self._records),
            "records": {k: v.to_dict() for k, v in self._records.items()},
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, default=str)

    def save(self, path: str | Path | None = None):
        target = Path(path) if path else self.store_path
        if target:
            target.write_text(self.to_json())

    def load(self, path: str | Path | None = None):
        target = Path(path) if path else self.store_path
        if target and target.exists():
            data = json.loads(target.read_text())
            for apath, rdata in data.get("records", {}).items():
                record = MetadataRecord(
                    artifact_path=rdata["artifact_path"],
                    semantic_type=rdata.get("semantic_type", "unknown"),
                    version=rdata.get("version", "0.1.0"),
                )
                for key, value in rdata.items():
                    if hasattr(record, key):
                        setattr(record, key, value)
                self._records[apath] = record
