"""Graph export generator — produces Neo4j-compatible Cypher and GraphML."""

import json
from pathlib import Path
from typing import Any

from genesis.compiler.codegen.base import CodeGenerator
from genesis.core.uir import CompilationUnit


class GraphGenerator(CodeGenerator):
    """Generates graph exports (Cypher, GraphML, JSON) from UIR."""

    def __init__(self):
        super().__init__("graph_generator", "graph")

    def generate(self, cu: CompilationUnit, output_dir: str | Path) -> list[Path]:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        generated = []

        # Export all graphs combined as Cypher
        all_nodes = {}
        all_edges = []

        for gname, graph in cu.all_graphs().items():
            for nid, node in graph.nodes.items():
                if nid not in all_nodes:
                    all_nodes[nid] = node
            all_edges.extend(graph.edges)

        if all_nodes:
            cypher = self._to_cypher(all_nodes, all_edges)
            cypher_path = output_dir / "graph.cypher"
            cypher_path.write_text(cypher)
            generated.append(cypher_path)

            graph_json = {
                "nodes": {nid: n.to_dict() for nid, n in all_nodes.items()},
                "edges": [e.to_dict() for e in all_edges],
            }
            json_path = output_dir / "graph.json"
            json_path.write_text(json.dumps(graph_json, indent=2, default=str))
            generated.append(json_path)

        return generated

    def _to_cypher(self, nodes: dict, edges: list) -> str:
        lines = [
            "// Generated by Venus Genesis-I Graph Generator",
            "// Neo4j Cypher Import Script",
            "",
        ]
        for nid, node in nodes.items():
            props = json.dumps({
                "id": nid,
                "label": node.label,
                "type": node.semantic_type,
            }, default=str)
            labels = node.semantic_type.replace(".", "_").upper()
            lines.append(f"CREATE (:{labels} {{id: '{nid}', {props[1:-1]}}})")

        lines.append("")
        for edge in edges:
            lines.append(
                f"MATCH (a {{id: '{edge.source}'}}), (b {{id: '{edge.target}'}}) "
                f"CREATE (a)-[:{edge.edge_type.upper().replace(' ', '_')}]->(b)"
            )

        lines.append("")
        lines.append(f"// Total: {len(nodes)} nodes, {len(edges)} edges")
        return "\n".join(lines)
